import type { GlobalThemeOverrides } from 'naive-ui'
export const archiveTheme: GlobalThemeOverrides = {
  common: {
    primaryColor: '#80b5f4',
    primaryColorHover: '#abcdf8',
    primaryColorPressed: '#6198d8',
    primaryColorSuppl: '#80b5f4',
    bodyColor: '#10151f',
    cardColor: '#192332',
    modalColor: '#192332',
    popoverColor: '#223047',
    inputColor: '#141d2b',
    tableColor: '#192332',
    borderColor: '#34445a',
    dividerColor: '#34445a',
    textColorBase: '#f1eee6',
    textColor1: '#f1eee6',
    textColor2: '#c3cddd',
    textColor3: '#a8b4c8',
    borderRadius: '2px',
    fontFamily: 'Inter, "Segoe UI", "Microsoft YaHei", sans-serif',
    successColor: '#68c7a0',
    infoColor: '#80b5f4',
    warningColor: '#e7bb73',
    errorColor: '#ef8a8a'
  },
  Button: {
    colorPrimary: '#e8bc72',
    colorHoverPrimary: '#f4d8a3',
    colorPressedPrimary: '#d5a75c',
    colorFocusPrimary: '#f4d8a3',
    colorDisabledPrimary: '#e8bc72',
    borderPrimary: '1px solid #e8bc72',
    borderHoverPrimary: '1px solid #f4d8a3',
    borderPressedPrimary: '1px solid #d5a75c',
    borderFocusPrimary: '1px solid #f4d8a3',
    borderDisabledPrimary: '1px solid #e8bc72',
    textColorPrimary: '#10151f',
    textColorHoverPrimary: '#10151f',
    textColorPressedPrimary: '#10151f',
    textColorFocusPrimary: '#10151f',
    textColorDisabledPrimary: '#10151f',
    borderRadiusMedium: '2px'
  },
  Input: { borderRadius: '2px', caretColor: '#80b5f4' },
  Card: { borderRadius: '2px' }
}

export const archiveLightTheme: GlobalThemeOverrides = {
  common: {
    ...archiveTheme.common,
    primaryColor: '#315f92',
    primaryColorHover: '#244d79',
    primaryColorPressed: '#234c79',
    primaryColorSuppl: '#315f92',
    bodyColor: '#f7f5ef',
    cardColor: '#fffdf8',
    modalColor: '#fffdf8',
    popoverColor: '#fffdf8',
    inputColor: '#fffdf8',
    tableColor: '#fffdf8',
    borderColor: '#cecfc8',
    dividerColor: '#cecfc8',
    textColorBase: '#233247',
    textColor1: '#233247',
    textColor2: '#46576b',
    textColor3: '#59697a',
    placeholderColor: '#6a7785',
    successColor: '#267454',
    infoColor: '#315f92',
    warningColor: '#8a5f26',
    errorColor: '#b3414a'
  },
  Button: {
    colorPrimary: '#8a5f26',
    colorHoverPrimary: '#71491a',
    colorPressedPrimary: '#624018',
    colorFocusPrimary: '#71491a',
    colorDisabledPrimary: '#8a5f26',
    borderPrimary: '1px solid #8a5f26',
    borderHoverPrimary: '1px solid #71491a',
    borderPressedPrimary: '1px solid #624018',
    borderFocusPrimary: '1px solid #71491a',
    borderDisabledPrimary: '1px solid #8a5f26',
    textColorPrimary: '#fffdf8',
    textColorHoverPrimary: '#fffdf8',
    textColorPressedPrimary: '#fffdf8',
    textColorFocusPrimary: '#fffdf8',
    textColorDisabledPrimary: '#fffdf8',
    borderRadiusMedium: '2px'
  },
  Input: { borderRadius: '2px', caretColor: '#315f92' },
  Card: { borderRadius: '2px' }
}
