import type { GlobalThemeOverrides } from 'naive-ui'
export const archiveTheme: GlobalThemeOverrides = {
  common: {
    primaryColor: '#80b5f4',
    primaryColorHover: '#abcdf8',
    primaryColorPressed: '#6198d8',
    primaryColorSuppl: '#80b5f4',
    bodyColor: '#10151f',
    cardColor: '#192332',
    modalColor: '#192332',
    popoverColor: '#223047',
    inputColor: '#141d2b',
    tableColor: '#192332',
    borderColor: '#34445a',
    dividerColor: '#34445a',
    textColorBase: '#f1eee6',
    textColor1: '#f1eee6',
    textColor2: '#c3cddd',
    textColor3: '#a8b4c8',
    borderRadius: '2px',
    fontFamily: 'Inter, "Segoe UI", "Microsoft YaHei", sans-serif',
    successColor: '#68c7a0',
    infoColor: '#80b5f4',
    warningColor: '#e7bb73',
    errorColor: '#ef8a8a'
  },
  Button: {
    colorPrimary: '#e8bc72',
    colorHoverPrimary: '#f4d8a3',
    colorPressedPrimary: '#d5a75c',
    colorFocusPrimary: '#f4d8a3',
    colorDisabledPrimary: '#e8bc72',
    borderPrimary: '1px solid #e8bc72',
    borderHoverPrimary: '1px solid #f4d8a3',
    borderPressedPrimary: '1px solid #d5a75c',
    borderFocusPrimary: '1px solid #f4d8a3',
    borderDisabledPrimary: '1px solid #e8bc72',
    textColorPrimary: '#10151f',
    textColorHoverPrimary: '#10151f',
    textColorPressedPrimary: '#10151f',
    textColorFocusPrimary: '#10151f',
    textColorDisabledPrimary: '#10151f',
    borderRadiusMedium: '2px'
  },
  Input: { borderRadius: '2px', caretColor: '#80b5f4' },
  Card: { borderRadius: '2px' }
}
